(()=>{'use strict';
const DB='pasevsu-pgp-ha-v1', STORE='state', STATE='workspace'; let state={schema:'pasevsu-pgp-workspace-v1',identity:{},architecture:{name:'PasevSU Universal MAX',rotation:'manual',slots:[]},generations:[],audit:[]};
const $=id=>document.getElementById(id), now=()=>new Date().toISOString(), uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function toast(s){const t=$('toast');t.textContent=s;t.style.display='block';setTimeout(()=>t.style.display='none',2600)}
function audit(action,detail={}){state.audit.unshift({id:uid(),ts:now(),action,detail});state.audit=state.audit.slice(0,2000);save();renderDashboard();}
function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function save(){const d=await db();return new Promise((ok,no)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(state,STATE);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
async function load(){const d=await db();return new Promise(ok=>{const tx=d.transaction(STORE);const r=tx.objectStore(STORE).get(STATE);r.onsuccess=()=>{if(r.result)state=r.result;ok()};r.onerror=()=>ok()})}
function identityForm(){ $('identityMaxMount').innerHTML=`<div class="row"><label>Full name *<input id="keyName"></label><label>Primary email<input id="keyEmail" type="email"></label><label>Given name<input id="keyGivenName"></label><label>Middle name<input id="keyMiddleName"></label><label>Family name<input id="keyFamilyName"></label><label>Prefix / suffix<div class="row"><input id="keyNamePrefix"><input id="keyNameSuffix"></div></label><label>Comment<input id="keyComment"></label><label>Additional emails<textarea id="keyAdditionalEmails"></textarea></label><label>Organization<input id="keyOrganization"></label><label>Organizational unit<input id="keyOrgUnit"></label><label>Title<input id="keyTitle"></label><label>Role<input id="keyRole"></label><label>Phones<textarea id="keyPhones"></textarea></label><label>URLs<textarea id="keyUrls"></textarea></label><label>Street<input id="keyStreet"></label><label>City<input id="keyCity"></label><label>Region<input id="keyRegion"></label><label>Postal code<input id="keyPostalCode"></label><label>Country<input id="keyCountry"></label><label>Case ID<input id="keyCaseId"></label><label>Evidence ID<input id="keyEvidenceId"></label><label>Operator ID<input id="keyOperatorId"></label><label>Tags<textarea id="keyTags"></textarea></label><label>Notes<textarea id="keyProfileNotes"></textarea></label><label>Notation DNS domain<input id="keyNotationDomain"></label><label>Custom notations<textarea id="keyCustomNotations" placeholder="name=value"></textarea></label></div><label><span><input id="keyEmbedNotations" type="checkbox" style="width:auto"> Embed signed notations in newly generated keys</span></label><div class="actions"><button id="saveIdentity" class="primary">Save identity</button><button id="exportIdentity" class="ghost">Export identity JSON</button></div>`;
 $('saveIdentity').onclick=()=>{state.identity=readIdentity();audit('IDENTITY_SAVED',{name:state.identity.name,emails:state.identity.emails});toast('Identity saved')}; $('exportIdentity').onclick=()=>download('pasevsu_identity.json',state.identity); }
function readIdentity(){const v=id=>$(id)?.value?.trim()||'', lines=id=>v(id).split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean);return {schema:'pasevsu-identity-profile-v1',name:v('keyName'),givenName:v('keyGivenName'),middleName:v('keyMiddleName'),familyName:v('keyFamilyName'),prefix:v('keyNamePrefix'),suffix:v('keyNameSuffix'),primaryEmail:v('keyEmail'),emails:[...new Set([v('keyEmail'),...lines('keyAdditionalEmails')].filter(Boolean))],comment:v('keyComment'),organization:v('keyOrganization'),organizationalUnit:v('keyOrgUnit'),title:v('keyTitle'),role:v('keyRole'),phones:lines('keyPhones'),urls:lines('keyUrls'),address:{street:v('keyStreet'),city:v('keyCity'),region:v('keyRegion'),postalCode:v('keyPostalCode'),country:v('keyCountry')},caseId:v('keyCaseId'),evidenceId:v('keyEvidenceId'),operatorId:v('keyOperatorId'),tags:lines('keyTags'),notes:v('keyProfileNotes'),notationDomain:v('keyNotationDomain'),embedNotations:!!$('keyEmbedNotations')?.checked,customNotations:lines('keyCustomNotations'),updatedAt:now()}}
function fillIdentity(){const p=state.identity||{},set=(id,v)=>{if($(id))$(id).value=v||''};set('keyName',p.name);set('keyEmail',p.primaryEmail);set('keyGivenName',p.givenName);set('keyMiddleName',p.middleName);set('keyFamilyName',p.familyName);set('keyNamePrefix',p.prefix);set('keyNameSuffix',p.suffix);set('keyComment',p.comment);set('keyAdditionalEmails',(p.emails||[]).filter(x=>x!==p.primaryEmail).join('\n'));set('keyOrganization',p.organization);set('keyOrgUnit',p.organizationalUnit);set('keyTitle',p.title);set('keyRole',p.role);set('keyPhones',(p.phones||[]).join('\n'));set('keyUrls',(p.urls||[]).join('\n'));for(const [k,id] of Object.entries({street:'keyStreet',city:'keyCity',region:'keyRegion',postalCode:'keyPostalCode',country:'keyCountry'}))set(id,p.address?.[k]);set('keyCaseId',p.caseId);set('keyEvidenceId',p.evidenceId);set('keyOperatorId',p.operatorId);set('keyTags',(p.tags||[]).join('\n'));set('keyProfileNotes',p.notes);set('keyNotationDomain',p.notationDomain);set('keyCustomNotations',(p.customNotations||[]).join('\n'));if($('keyEmbedNotations'))$('keyEmbedNotations').checked=!!p.embedNotations}
function addSlot(data={}){state.architecture.slots.push({id:uid(),name:data.name||`Internal Key ${state.architecture.slots.length+1}`,role:data.role||'encrypt',algorithm:data.algorithm||'rsa',strength:data.strength||'4096',status:'empty',createdAt:now()});renderSlots()}
function renderSlots(){const h=$('slots');h.innerHTML='';state.architecture.slots.forEach((s,i)=>{const e=document.createElement('div');e.className='slot';e.innerHTML=`<div class="slotgrid"><label>Slot name<input data-k="name" value="${esc(s.name)}"></label><label>Role<select data-k="role"><option value="certify">Certify</option><option value="sign">Sign</option><option value="encrypt">Encrypt</option><option value="authenticate">Authenticate</option></select></label><label>Algorithm<select data-k="algorithm"><option value="rsa">RSA</option><option value="ecc">ECC / Curve25519</option></select></label><label>Strength<select data-k="strength"><option>3072</option><option>4096</option><option>8192</option><option>16384</option></select></label><button class="remove">Remove</button></div><span class="badge">${s.status||'empty'}</span><span class="badge">slot ${i+1}</span>`;e.querySelector('[data-k=role]').value=s.role;e.querySelector('[data-k=algorithm]').value=s.algorithm;e.querySelector('[data-k=strength]').value=s.strength;e.querySelectorAll('[data-k]').forEach(x=>x.onchange=()=>s[x.dataset.k]=x.value);e.querySelector('.remove').onclick=()=>{state.architecture.slots=state.architecture.slots.filter(x=>x.id!==s.id);audit('KEY_SLOT_REMOVED',{slotId:s.id,name:s.name});renderSlots()};h.append(e)})}
async function generateSlot(slot,reason='initial'){if(!window.openpgp)throw Error('OpenPGP runtime unavailable');const p=state.identity;if(!p?.name)throw Error('Save Identity MAX first');const pass=prompt(`Passphrase for ${slot.name} (minimum 16 characters):`);if(!pass||pass.length<16)throw Error('Passphrase must contain at least 16 characters');const userIDs=(p.emails?.length?p.emails:[p.primaryEmail||'']).map(email=>email?{name:p.name,email}:{name:p.name});const opts={userIDs,passphrase,format:'armored'};if(slot.algorithm==='rsa'){opts.type='rsa';opts.rsaBits=Math.max(2048,Number(slot.strength)||4096)}else{opts.type='ecc';opts.curve='curve25519'};const out=await openpgp.generateKey(opts);const key=await openpgp.readKey({armoredKey:out.publicKey});const fpr=key.getFingerprint().toUpperCase();const previous=state.generations.find(g=>g.slotId===slot.id&&g.status==='active');if(previous){previous.status='superseded';previous.supersededAt=now();previous.supersededBy=fpr}const gen={id:uid(),slotId:slot.id,slotName:slot.name,role:slot.role,algorithm:slot.algorithm,strength:slot.strength,fingerprint:fpr,status:'active',generation:(Math.max(0,...state.generations.filter(g=>g.slotId===slot.id).map(g=>g.generation||0))+1),createdAt:now(),reason,identitySnapshot:structuredClone(p),publicKey:out.publicKey,privateKey:out.privateKey};state.generations.unshift(gen);slot.status='active';slot.activeFingerprint=fpr;slot.updatedAt=now();audit(previous?'KEY_ROTATED':'KEY_GENERATED',{slotId:slot.id,fingerprint:fpr,previousFingerprint:previous?.fingerprint||null,reason});await save();renderAll();return gen}
function renderVault(){const h=$('vaultList');h.innerHTML='';if(!state.generations.length){h.innerHTML='<div class="empty">No generated key generations.</div>';return}state.generations.forEach(g=>{const e=document.createElement('div');e.className='vaultitem';e.innerHTML=`<div class="panelhead"><div><b>${esc(g.slotName)}</b> <span class="badge">${g.status}</span> <span class="badge">generation ${g.generation}</span></div><code>${g.fingerprint}</code></div><div class="vaultmeta"><span>Role: ${g.role}</span><span>${g.algorithm.toUpperCase()} ${g.strength}</span><span>Created: ${g.createdAt}</span><span>Reason: ${g.reason}</span></div><div class="vaultactions"><button class="ghost pub">Public .asc</button><button class="ghost priv">Private .asc</button><button class="primary rotate">Replace / rotate</button><button class="danger revoke">Mark revoked</button></div>`;e.querySelector('.pub').onclick=()=>download(`${g.slotName}_public.asc`,g.publicKey,'application/pgp-keys');e.querySelector('.priv').onclick=()=>download(`${g.slotName}_private.asc`,g.privateKey,'application/pgp-keys');e.querySelector('.rotate').onclick=async()=>{const slot=state.architecture.slots.find(s=>s.id===g.slotId);if(!slot)return;try{await generateSlot(slot,'manual-replacement')}catch(x){toast(x.message)}};e.querySelector('.revoke').onclick=()=>{g.status='revoked';g.revokedAt=now();audit('KEY_MARKED_REVOKED',{fingerprint:g.fingerprint});renderAll()};h.append(e)})}
function renderDashboard(){const active=state.architecture.slots.filter(s=>s.status==='active').length;$('mIdentity').textContent=state.identity?.name||'Not configured';$('mSlots').textContent=`${active} / ${state.architecture.slots.length}`;$('mGenerations').textContent=state.generations.length;$('mRuntime').textContent=window.openpgp?'Ready':'Unavailable';$('architectureSummary').innerHTML=state.architecture.slots.length?state.architecture.slots.map(s=>`<div class="auditline"><b>${esc(s.name)}</b> · ${s.role} · ${s.algorithm.toUpperCase()} ${s.strength} <span class="badge">${s.status}</span></div>`).join(''):'No architecture configured.';$('auditSummary').innerHTML=state.audit.length?state.audit.slice(0,7).map(a=>`<div class="auditline"><b>${a.action}</b><br><small>${a.ts}</small></div>`).join(''):'No events yet.'}
function renderMetadata(){$('metadataDump').textContent=JSON.stringify({...state,integrity:{openpgpVersion:'6.3.1-pinned-build',secureContext:isSecureContext,indexedDB:!!indexedDB,webCrypto:!!crypto?.subtle,exportedAt:now()}},null,2)}
function renderAll(){renderSlots();renderVault();renderDashboard();renderMetadata()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function download(name,data,type='application/json'){const body=typeof data==='string'?data:JSON.stringify(data,null,2),u=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const TEXT_HASH_LABELS=[['md5','MD5'],['sha1','SHA-1'],['sha224','SHA-224'],['sha256','SHA-256'],['sha384','SHA-384'],['sha512','SHA-512'],['sha3_224','SHA3-224'],['sha3_256','SHA3-256'],['sha3_384','SHA3-384'],['sha3_512','SHA3-512'],['ripemd160','RIPEMD-160']];
let textManifestCase=null,textManifestCanonical=null;
async function textManifestFor(text,operation='HASH_TIMESTAMP_MANIFEST',recipientFingerprint=''){
 const bytes=new TextEncoder().encode(text); return apiJson('api/text/manifest',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Text-Operation':operation,'X-Text-Source':'textarea-dom-value-to-utf8','X-Recipient-Fingerprint':recipientFingerprint},body:bytes});
}
function renderTextHashes(m){const rows=$('tmHashRows');if(!rows)return;rows.innerHTML=TEXT_HASH_LABELS.map(([k,n])=>`<tr><td>${n}</td><td>${esc(m?.hashes?.[k]??'UNAVAILABLE')}</td></tr>`).join('')}
async function createTextCase(text,operation='HASH_TIMESTAMP_MANIFEST',recipientFingerprint=''){
 const bytes=new TextEncoder().encode(text),name=`text_manifest_${new Date().toISOString().replace(/[:.]/g,'-')}.json`;
 const x=await apiJson('api/text/case',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':name,'X-Text-Operation':operation,'X-Text-Source':'textarea-dom-value-to-utf8','X-Recipient-Fingerprint':recipientFingerprint},body:bytes});
 if(x.ok){textManifestCase=x.case;textManifestCanonical=x.canonicalManifest;evidenceCase=x.case} return x;
}
async function encrypt(){try{
 const key=await openpgp.readKey({armoredKey:$('encPub').value}),fp=key.getFingerprint().toUpperCase(),plain=$('encText').value;
 const pm=await textManifestFor(plain,'OPENPGP_ENCRYPT',fp); const msg=await openpgp.createMessage({text:plain}); const cipher=await openpgp.encrypt({message:msg,encryptionKeys:key}); $('encOut').value=cipher;
 const cm=await textManifestFor(cipher,'OPENPGP_CIPHERTEXT',fp); const c=await createTextCase(plain,'OPENPGP_ENCRYPT',fp);
 if(c.ok){const binding={schema:'pasevsu-text-encryption-binding/v1',plaintext:pm.hashes,ciphertext:cm.hashes,recipientFingerprint:fp,case:c.case,createdAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(binding,null,2)],{type:'application/json'});await fetch('api/case/artifact',{method:'POST',headers:{'X-Case-ID':c.case,'X-Artifact-Kind':'artifact','X-File-Name':'text_encryption_binding.json'},body:blob});
   const tsa=await fetch('api/tsa/stamp',{method:'POST',headers:{'X-Case-ID':c.case,'X-TSA-Label':'TEXT_START','X-TSA-Provider':'DFN'},body:new TextEncoder().encode(c.canonicalManifest)}).then(r=>r.json()).catch(e=>({ok:false,error:e.message}));
   audit('TEXT_EVIDENCE_CASE_CREATED',{case:c.case,manifestSha256:c.manifestSha256,timestamp:tsa.ok?'PASS':'PENDING_OR_FAILED'});
 }
 audit('MESSAGE_ENCRYPTED',{recipient:fp,plaintextSha256:pm.hashes?.sha256,ciphertextSha256:cm.hashes?.sha256,textEvidenceCase:c.case||null});
 }catch(e){toast(e.message)}}
async function bindTextManifest(){
 const text=()=>$('tmText').value;
 $('tmHashes').onclick=async()=>{const m=await textManifestFor(text());renderTextHashes(m);$('tmStatus').textContent=`${m.byteLength} UTF-8 bytes · SHA-256 ${m.hashes?.sha256||'—'}`};
 $('tmManifest').onclick=async()=>{const c=await createTextCase(text());renderTextHashes(c.manifest);$('tmOut').value=JSON.stringify(c.manifest,null,2);$('tmStatus').textContent=c.ok?`Case ${c.case} · manifest ${c.manifestSha256}`:`FAILED: ${c.error}`};
 $('tmTsa').onclick=async()=>{if(!textManifestCase){const c=await createTextCase(text());if(!c.ok)return toast(c.error||'Manifest case failed')};const x=await fetch('api/tsa/stamp',{method:'POST',headers:{'X-Case-ID':textManifestCase,'X-TSA-Label':'TEXT_START','X-TSA-Provider':'DFN'},body:new TextEncoder().encode(textManifestCanonical)}).then(r=>r.json());$('tmStatus').textContent=x.ok?`RFC3161 PASS · ${textManifestCase}`:`RFC3161 FAILED · ${x.error||'validation failed'}`};
 $('tmOts').onclick=async()=>{const m=await textManifestFor(text());const canonical=m.canonicalCore||JSON.stringify(m);const f=new File([canonical],`text_manifest_${Date.now()}.json`,{type:'application/json'});const x=await apiBinary('api/ots/stamp',f);if(x.ok){textManifestCase=x.case;evidenceCase=x.case}$('tmStatus').textContent=x.ok?`OTS created · ${x.case} · ${x.state}`:`OTS FAILED · ${x.error}`};
}
async function decrypt(){try{let key=await openpgp.readPrivateKey({armoredKey:$('decPriv').value});key=await openpgp.decryptKey({privateKey:key,passphrase:$('decPass').value});const msg=await openpgp.readMessage({armoredMessage:$('decText').value});const {data}=await openpgp.decrypt({message:msg,decryptionKeys:key});$('decOut').value=data;audit('MESSAGE_DECRYPTED',{key:key.getFingerprint().toUpperCase()})}catch(e){toast(e.message)}}
async function sign(){try{let key=await openpgp.readPrivateKey({armoredKey:$('sigPriv').value});key=await openpgp.decryptKey({privateKey:key,passphrase:$('sigPass').value});const msg=await openpgp.createMessage({text:$('sigText').value});$('sigOut').value=await openpgp.sign({message:msg,signingKeys:key,detached:true});audit('DETACHED_SIGNATURE_CREATED',{key:key.getFingerprint().toUpperCase()})}catch(e){toast(e.message)}}
async function verify(){try{const key=await openpgp.readKey({armoredKey:$('verPub').value}),msg=await openpgp.createMessage({text:$('verText').value}),sig=await openpgp.readSignature({armoredSignature:$('verSig').value});const r=await openpgp.verify({message:msg,signature:sig,verificationKeys:key});await r.signatures[0].verified;$('verifyOut').textContent=`VALID · ${key.getFingerprint().toUpperCase()}`;audit('SIGNATURE_VERIFIED',{key:key.getFingerprint().toUpperCase(),valid:true})}catch(e){$('verifyOut').textContent=`FAILED · ${e.message}`;audit('SIGNATURE_VERIFIED',{valid:false,error:e.message})}}
let evidenceCurrentFile=null,evidenceOps=[],evidenceCase=null,evidenceCaseTimer=null;
async function apiJson(endpoint,options={}){const r=await fetch(endpoint,options);const x=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`}));if(!r.ok&&x.ok!==false)x.ok=false;return x}
async function apiBinary(endpoint,file,headers={}){const r=await fetch(endpoint,{method:'POST',headers:{'X-File-Name':file.name,...headers},body:file});const data=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`}));if(!r.ok&&data.ok!==false)data.ok=false;return data}
function prettyEvidence(x){return JSON.stringify(x,null,2)}
function artifactLinks(x){const items=[];if(x?.downloadUrl)items.push({file:x.otsFile||'artifact',url:x.downloadUrl});for(const a of x?.downloadUrls||[])items.push(a);if(!items.length)return '';return '<div class="artifactlinks">'+items.map(a=>`<a class="ghost" href="${esc(a.url)}" download>${esc(a.file)}</a>`).join('')+'</div>'}
async function evidenceStatus(){try{const r=await fetch('api/status',{cache:'no-store'}),x=await r.json();const set=(id,ready,yes,no)=>{const e=$(id);e.textContent=ready?yes:no;e.className=ready?'ready':'missing'};set('evBackend',true,'READY','UNAVAILABLE');set('evOts',!!x.runtimes?.ots?.ready,`READY · ${x.runtimes?.ots?.engine||'OTS'}`,'MISSING · add _crypto/javascript-opentimestamps');set('evTsa',!!x.runtimes?.tsaPki?.ready,'READY · OpenSSL + strict PKI','MISSING · OpenSSL/CA store');return x}catch(e){$('evBackend').textContent='UNAVAILABLE';$('evBackend').className='missing';throw e}}
async function digestFile(f){const b=await f.arrayBuffer(),h=async a=>Array.from(new Uint8Array(await crypto.subtle.digest(a,b))).map(x=>x.toString(16).padStart(2,'0')).join('');const [s256,s512]=await Promise.all([h('SHA-256'),h('SHA-512')]);$('fileDigest').innerHTML=`<b>${esc(f.name)}</b><br>Bytes: ${f.size}<br>SHA-256: <code>${s256}</code><br>SHA-512: <code>${s512}</code>`;return {name:f.name,bytes:f.size,sha256:s256,sha512:s512}}
function logEvidence(action,result){const item={ts:now(),action,result};evidenceOps.unshift(item);evidenceOps=evidenceOps.slice(0,100);$('evidenceLog').textContent=prettyEvidence(evidenceOps);audit(action,result)}
async function doOtsStamp(){if(!evidenceCurrentFile)return toast('Choose an evidence file first');$('otsResult').textContent='Backing up original, verifying hashes and creating OTS…';const x=await apiBinary('api/ots/stamp',evidenceCurrentFile);$('otsResult').textContent=prettyEvidence(x);$('otsResult').insertAdjacentHTML('afterend',artifactLinks(x));if(x.case){evidenceCase=x.case;startCasePolling()}logEvidence('OTS_STAMP',x)}
async function doOtsAction(kind){if(!evidenceCase)return toast('Create/open an evidence case first');$('otsResult').textContent=`${kind} active case…`;const x=await apiJson(`api/ots/${kind}`,{method:'POST',headers:{'X-Case-ID':evidenceCase}});$('otsResult').textContent=prettyEvidence(x);$('otsResult').insertAdjacentHTML('afterend',artifactLinks(x));logEvidence(`OTS_${kind.toUpperCase()}`,x);await refreshCaseStatus().catch(()=>{})}

async function refreshCaseStatus(){if(!evidenceCase)return;const r=await fetch(`api/case/status?case=${encodeURIComponent(evidenceCase)}`,{cache:'no-store'}),x=await r.json();const st=x.state||{};$('caseStatus').innerHTML=`<b>Case:</b> ${esc(evidenceCase)}<br><b>State:</b> <span class="badge">${esc(st.state||'UNKNOWN')}</span><br><b>Attempt:</b> ${st.attempt||0}<br><b>Next:</b> ${esc(st.nextAttemptAt||'—')}<br><b>Bitcoin block:</b> ${esc((st.blockchain?.blockHeights||[]).join(', ')||'pending')}`;if(st.state==='BLOCKCHAIN_VERIFIED'&&evidenceCaseTimer){clearInterval(evidenceCaseTimer);evidenceCaseTimer=null}return x}
function startCasePolling(){refreshCaseStatus().catch(()=>{});if(evidenceCaseTimer)clearInterval(evidenceCaseTimer);evidenceCaseTimer=setInterval(()=>refreshCaseStatus().catch(()=>{}),15000)}
async function confirmCaseNow(){if(!evidenceCase)return toast('Create OTS first');const r=await fetch('api/ots/confirm-now',{method:'POST',headers:{'X-Case-ID':evidenceCase}}),x=await r.json();$('otsResult').textContent=prettyEvidence(x);logEvidence('OTS_CONFIRM_NOW',x);await refreshCaseStatus()}
async function addCaseArtifact(){if(!evidenceCase)return toast('Create OTS first');const f=$('caseArtifactFile').files[0];if(!f)return toast('Choose an artifact file');const x=await apiBinary('api/case/artifact',f,{'X-Case-ID':evidenceCase,'X-Artifact-Kind':$('artifactKind').value});$('artifactResult').textContent=prettyEvidence(x);logEvidence('CASE_ARTIFACT_ADDED',x)}

async function caseControl(action){if(!evidenceCase)return toast('Create/open an evidence case first');const map={preflight:['api/case/preflight-verify','POST'],finalize:['api/case/finalize','POST'],seal:['api/case/seal-verify','GET']},cfg=map[action];let url=cfg[0],opt={method:cfg[1],headers:{'X-Case-ID':evidenceCase}};if(action==='seal'){url+=`?case=${encodeURIComponent(evidenceCase)}`;opt={method:'GET'}}const x=await apiJson(url,opt);$('closureResult').textContent=prettyEvidence(x);logEvidence(`CASE_${action.toUpperCase()}`,x);await refreshCaseStatus().catch(()=>{});return x}
async function doTsa(label){if(!evidenceCase)return toast('Create OTS first so the immutable evidence case exists');$('tsaResult').textContent=`Creating and strictly validating ${label} RFC3161 timestamp…`;const endpoint=label==='START'?'api/tsa/start':'api/tsa/stop';const x=await apiJson(endpoint,{method:'POST',headers:{'X-Case-ID':evidenceCase}});$('tsaResult').textContent=prettyEvidence(x);logEvidence(`TSA_${label}`,x);await refreshCaseStatus().catch(()=>{})}
function bindEvidence(){if(!$('evidenceFile'))return;$('refreshEvidenceStatus').onclick=()=>evidenceStatus().catch(e=>toast(e.message));$('evidenceFile').onchange=async e=>{evidenceCurrentFile=e.target.files[0]||null;if(evidenceCurrentFile)await digestFile(evidenceCurrentFile)};$('otsStamp').onclick=()=>doOtsStamp().catch(e=>toast(e.message));$('otsUpgrade').onclick=()=>doOtsAction('upgrade').catch(e=>toast(e.message));$('otsVerify').onclick=()=>doOtsAction('verify').catch(e=>toast(e.message));$('otsConfirmNow').onclick=()=>confirmCaseNow().catch(e=>toast(e.message));$('addCaseArtifact').onclick=()=>addCaseArtifact().catch(e=>toast(e.message));$('tsaStart').onclick=()=>doTsa('START').catch(e=>toast(e.message));$('tsaStop').onclick=()=>doTsa('STOP').catch(e=>toast(e.message));$('casePreflight').onclick=()=>caseControl('preflight').catch(e=>toast(e.message));$('caseFinalize').onclick=()=>caseControl('finalize').catch(e=>toast(e.message));$('caseSealVerify').onclick=()=>caseControl('seal').catch(e=>toast(e.message));evidenceStatus().catch(()=>{})}
async function init(){identityForm();bindEvidence();bindTextManifest();await load();fillIdentity();$('archName').value=state.architecture.name||'';$('rotationPolicy').value=state.architecture.rotation||'manual';document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`view-${b.dataset.view}`).classList.add('active');$('pageTitle').textContent=b.textContent.replace(/^\S+\s/,'');if(b.dataset.view==='metadata')renderMetadata()});$('addSlot').onclick=()=>{addSlot();audit('KEY_SLOT_ADDED',{count:state.architecture.slots.length})};$('saveArchitecture').onclick=()=>{state.architecture.name=$('archName').value;state.architecture.rotation=$('rotationPolicy').value;audit('ARCHITECTURE_SAVED',{slots:state.architecture.slots.length});toast('Architecture saved')};$('generateMissing').onclick=async()=>{for(const s of state.architecture.slots.filter(x=>x.status!=='active'))try{await generateSlot(s,'architecture-generation')}catch(e){toast(e.message);break}};$('encryptBtn').onclick=encrypt;$('decryptBtn').onclick=decrypt;$('signBtn').onclick=sign;$('verifyBtn').onclick=verify;$('exportAll').onclick=()=>download(`pasevsu_metadata_${Date.now()}.json`,state);$('clearAudit').onclick=()=>{if(confirm('Clear audit history?')){state.audit=[];save();renderAll()}};$('lockVault').onclick=()=>{document.querySelectorAll('textarea').forEach(x=>x.value='');toast('Sensitive text fields cleared')};if(!state.architecture.slots.length){['Certify / Primary','Signing','Encryption','Authentication'].forEach((n,i)=>addSlot({name:n,role:['certify','sign','encrypt','authenticate'][i],algorithm:i?'ecc':'rsa',strength:i?'4096':'4096'}));audit('DEFAULT_ARCHITECTURE_CREATED',{slots:4})}renderAll();setTimeout(()=>{const ok=!!window.openpgp;$('runtimeDot').classList.toggle('ok',ok);$('runtimeText').textContent=ok?'OpenPGP runtime ready':'OpenPGP runtime unavailable';renderDashboard()},400)}
document.addEventListener('DOMContentLoaded',init);
})();
