(()=>{'use strict';
const $=id=>document.getElementById(id);
const HELP={
 profile:['Криптографски профил','Профилът задава желаната архитектура. Генерираният ключ се приема само след обратно прочитане и проверка. Пример: RSA-8192 трябва действително да е RSA 8192, без silent downgrade.'],
 emailRecipient:['Получател по e-mail','Търси точен e-mail в локалния Vault. Преди криптиране се показва fingerprint и се изисква потвърждение. Пример: recipient@example.com.'],
 textEvidence:['Точен текстов вход','Хешира се точната UTF-8 byte последователност. Интервали и нови редове се запазват. Пример: „Договор № 42\\nВерсия: 1“.'],
 hashVerify:['Проверка на digest','Сравнява изчисления digest с очакван hex digest. MATCH означава идентични bytes за избрания алгоритъм.']
};
let tip;
function showHelp(el){const d=HELP[el.dataset.help];if(!d)return;tip?.remove();tip=document.createElement('div');tip.className='helpbox';const b=document.createElement('b');b.textContent=d[0];tip.append(b,document.createTextNode(d[1]));document.body.appendChild(tip);const r=el.getBoundingClientRect(),w=tip.offsetWidth,h=tip.offsetHeight;tip.style.left=Math.max(12,Math.min(innerWidth-w-12,r.left))+'px';tip.style.top=Math.max(12,Math.min(innerHeight-h-12,r.bottom+8))+'px'}
function hide(){tip?.remove();tip=null}
function normalizeEmail(v){return String(v||'').trim().toLowerCase()}
function keyHasExactEmail(key,email){const target=normalizeEmail(email);return key.getUserIDs().some(uid=>{const m=String(uid).match(/<([^<>]+)>\s*$/);return m?normalizeEmail(m[1])===target:normalizeEmail(uid)===target})}
async function inspectArmored(a){if(!window.openpgp||!a?.trim())throw Error('OpenPGP key is required');const k=await openpgp.readKey({armoredKey:a});let exp='unknown';try{const x=await k.getExpirationTime();exp=x instanceof Date?x.toISOString():String(x)}catch{};let enc='PASS';try{await k.getEncryptionKey()}catch{enc='FAIL'}return {key:k,fingerprint:k.getFingerprint().toUpperCase(),keyId:k.getKeyID().toHex().toUpperCase(),version:k.keyPacket?.version??'runtime-dependent',expiration:exp,encryption:enc}}
async function workspace(){const req=indexedDB.open('pasevsu-pgp-ha-v1');const db=await new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)});const tx=db.transaction('state','readonly'),g=tx.objectStore('state').get('workspace');return new Promise((res,rej)=>{g.onsuccess=()=>res(g.result||{});g.onerror=()=>rej(g.error)})}
function setStatus(msg,i){$('recipientStatus').textContent=msg;const d=$('recipientDetails');if(i)d.innerHTML=`<span>Source</span><b>${i.source}</b><span>Fingerprint</span><code>${i.fingerprint}</code><span>Key version</span><b>${i.version}</b><span>Encryption capability</span><b>${i.encryption}</b><span>Expiration</span><b>${i.expiration}</b>`}
async function localRecipient(){const email=normalizeEmail($('recipientEmail').value);if(!email)return setStatus('Въведете e-mail.');let found=null;try{const ws=await workspace();for(const x of ws.generations||[]){if(x.status!=='active'||!x.publicKey)continue;try{const inf=await inspectArmored(x.publicKey);if(keyHasExactEmail(inf.key,email)){found={...inf,armored:x.publicKey,source:'Local Vault'};break}}catch{}}}catch(e){return setStatus('Local Vault lookup FAILED: '+e.message)}if(!found)return setStatus('Няма точен активен public key за този e-mail в локалния Vault.');window.__recipient=found;$('emailPub').value=found.armored;$('recipientFingerprintConfirmed').checked=false;setStatus('Ключът е намерен. Проверете fingerprint-а преди криптиране.',found)}
async function emailEncrypt(){try{const email=normalizeEmail($('recipientEmail').value),inf=await inspectArmored($('emailPub').value);if(inf.encryption!=='PASS')throw Error('Key has no usable encryption capability');if(email&&!keyHasExactEmail(inf.key,email))throw Error('Public key does not contain the exact recipient e-mail');if(!$('recipientFingerprintConfirmed').checked)throw Error('Confirm recipient fingerprint first');const msg=await openpgp.createMessage({text:$('emailText').value}),opts={message:msg,encryptionKeys:inf.key};if($('emailSign').checked){let sk=await openpgp.readPrivateKey({armoredKey:$('emailSignPriv').value});sk=await openpgp.decryptKey({privateKey:sk,passphrase:$('emailSignPass').value});opts.signingKeys=sk} $('emailOut').value=await openpgp.encrypt(opts);setStatus($('emailSign').checked?'Sign + Encrypt PASS.':'Encryption PASS.',{...inf,source:window.__recipient?.source||'Manual key'})}catch(e){setStatus('Encryption FAILED: '+e.message)}}
const PROFILES={compat:{name:'Compatibility RSA-4096',slots:[['Certify / Primary','certify','rsa','4096'],['Signing','sign','rsa','4096'],['Encryption','encrypt','rsa','4096']]},rsa8192:{name:'RSA-8192',slots:[['Certify / Primary','certify','rsa','8192'],['Signing','sign','rsa','8192'],['Encryption','encrypt','rsa','8192']]},rsa16384:{name:'RSA-16384',slots:[['Certify / Primary','certify','rsa','16384'],['Signing','sign','rsa','16384'],['Encryption','encrypt','rsa','16384']]},modern:{name:'Modern ECC',slots:[['Certify / Primary','certify','ecc','curve25519'],['Signing','sign','ecc','curve25519'],['Encryption','encrypt','ecc','curve25519']]}};
function profileInfo(p){const M={compat:'RSA-4096 compatibility profile. Broad interoperability; generated key must verify as RSA 4096.',rsa8192:'High-strength RSA-8192 profile. Slower generation and larger signatures/keys.',rsa16384:'Extreme RSA-16384 profile. Runtime support and actual bit length must be verified; never silently downgraded.',modern:'Modern ECC profile. UI must report the real curve, never fictitious “ECC 4096”.',v6:'RFC 9580 / OpenPGP v6 target. Generation remains blocked until runtime capability and packet-version verification are implemented.',max:'Universal MAX target: real primary + specialized bound subkeys. Generation remains blocked until the primary/subkey builder is implemented.'};$('profileInfo').textContent=M[p]||'';const spec=PROFILES[p];if(!spec)return;if(window.ChronoSealEnterprise?.applyProfile)window.ChronoSealEnterprise.applyProfile(spec);else $('profileInfo').textContent+=' Profile application API unavailable: FAIL.'}
async function verifyText(){try{const alg=$('tmVerifyAlg').value.replace('-','').toLowerCase(),expected=$('tmExpected').value.replace(/\s+/g,'').toLowerCase();if(!/^[0-9a-f]+$/.test(expected))throw Error('Expected digest must be hexadecimal');const data=new TextEncoder().encode($('tmText').value),name={'sha256':'SHA-256','sha512':'SHA-512'}[alg];if(!name)throw Error('Browser verifier supports SHA-256/SHA-512 here; use backend manifest for SHA3');const b=await crypto.subtle.digest(name,data),got=[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join(''),need=name==='SHA-256'?64:128;if(expected.length!==need)throw Error(`Expected ${need} hex characters for ${name}`);$('tmVerifyOut').textContent=`${got===expected?'MATCH':'FAILED'}\nExpected: ${expected}\nCalculated: ${got}`;$('tmVerifyOut').dataset.status=got===expected?'pass':'fail'}catch(e){$('tmVerifyOut').textContent='FAILED: '+e.message;$('tmVerifyOut').dataset.status='fail'}}
function updateCounts(){const t=$('tmText')?.value||'';$('tmChars').textContent=[...t].length;$('tmBytes').textContent=new TextEncoder().encode(t).length}
async function renderMulti(){const host=$('multiRecipients');if(!host)return;try{const ws=await workspace(),keys=(ws.generations||[]).filter(x=>x.status==='active'&&x.publicKey);host.innerHTML=keys.length?'':'Няма активни public keys.';for(const [i,x] of keys.entries()){const row=document.createElement('label');row.className='checkline';const cb=document.createElement('input');cb.type='checkbox';cb.dataset.multiIndex=String(i);cb.__key=x;row.append(cb,document.createTextNode(` ${x.slotName} · ${x.fingerprint}`));host.append(row)}}catch(e){host.textContent='Vault read FAILED: '+e.message}}
async function multiEncrypt(){try{const c=[...document.querySelectorAll('#multiRecipients input:checked')];if(c.length<2)throw Error('Select at least two recipients');const keys=[];for(const cb of c){const inf=await inspectArmored(cb.__key.publicKey);if(inf.encryption!=='PASS')throw Error(`Recipient ${inf.fingerprint} has no encryption capability`);keys.push(inf.key)}const msg=await openpgp.createMessage({text:$('multiText').value});$('multiOut').value=await openpgp.encrypt({message:msg,encryptionKeys:keys})}catch(e){$('multiOut').value='FAILED: '+e.message}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.help').forEach(e=>{e.tabIndex=0;e.addEventListener('mouseenter',()=>showHelp(e));e.addEventListener('mouseleave',hide);e.addEventListener('focus',()=>showHelp(e));e.addEventListener('blur',hide)});$('helpMode')?.addEventListener('click',()=>document.body.classList.toggle('help-mode'));document.querySelectorAll('.opTab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.opTab,.opPane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('op-'+b.dataset.op)?.classList.add('active');if(b.dataset.op==='multi')renderMulti()});document.querySelectorAll('.profilechip').forEach(b=>b.onclick=()=>profileInfo(b.dataset.profile));$('recipientLocal')?.addEventListener('click',localRecipient);$('recipientUseManual')?.addEventListener('click',async()=>{try{const i=await inspectArmored($('emailPub').value),email=normalizeEmail($('recipientEmail').value);if(email&&!keyHasExactEmail(i.key,email))throw Error('Public key does not contain the exact recipient e-mail');window.__recipient={...i,source:'Manual key'};$('recipientFingerprintConfirmed').checked=false;setStatus('Manual key parsed. Verify fingerprint.',window.__recipient)}catch(e){setStatus('Manual key FAILED: '+e.message)}});$('emailSign')?.addEventListener('change',e=>$('emailSigningFields').hidden=!e.target.checked);$('emailEncrypt')?.addEventListener('click',emailEncrypt);$('multiEncrypt')?.addEventListener('click',multiEncrypt);$('tmText')?.addEventListener('input',updateCounts);$('tmExample')?.addEventListener('click',()=>{$('tmText').value='Договор № 42\nВерсия: 1\nДата: 2026-09-29';updateCounts()});$('tmVerify')?.addEventListener('click',verifyText);updateCounts()});
})();
