#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const ROOT=process.argv[2]||'/opt/pasevsu',CRYPTO=path.join(ROOT,'_crypto');
const failures=[],checks=[];
function rec(name,ok,detail={}){checks.push({name,ok,...detail});if(!ok)failures.push(name)}
function run(bin,args,timeout=30000){try{const r=cp.spawnSync(bin,args,{encoding:'utf8',timeout,maxBuffer:8*1024*1024});return {ok:r.status===0,status:r.status,stdout:String(r.stdout||''),stderr:String(r.stderr||''),error:r.error?.message||null}}catch(e){return {ok:false,error:e.message}}}
(async()=>{
 rec('openssl.binary',fs.existsSync('/usr/bin/openssl'));if(fs.existsSync('/usr/bin/openssl'))rec('openssl.exec',run('/usr/bin/openssl',['version']).ok);
 const vendor=path.join(ROOT,'app/vendor/openpgp.min.js');rec('openpgp.browser.bundle',fs.existsSync(vendor)&&fs.statSync(vendor).size>100000,{path:vendor,bytes:fs.existsSync(vendor)?fs.statSync(vendor).size:0});
 try{const pkg=require.resolve('openpgp/package.json',{paths:[ROOT]}),j=JSON.parse(fs.readFileSync(pkg));rec('openpgp.node.package',j.version==='6.3.1',{version:j.version});const mod=await import(path.join(ROOT,'node_modules/openpgp/dist/node/openpgp.mjs'));const {privateKey,publicKey}=await mod.generateKey({type:'ecc',curve:'curve25519Legacy',userIDs:[{name:'PasevSU Runtime Selftest'}],passphrase:'selftest-only'});let pk=await mod.readPrivateKey({armoredKey:privateKey});pk=await mod.decryptKey({privateKey:pk,passphrase:'selftest-only'});const pub=await mod.readKey({armoredKey:publicKey}),msg=await mod.createMessage({text:'pasevsu-runtime-selftest'}),sig=await mod.sign({message:msg,signingKeys:pk,detached:true}),sg=await mod.readSignature({armoredSignature:sig}),vr=await mod.verify({message:msg,signature:sg,verificationKeys:pub});await vr.signatures[0].verified;rec('openpgp.crypto.roundtrip',true,{fingerprint:pub.getFingerprint().toUpperCase()})}catch(e){rec('openpgp.node.package',false,{error:e.message});rec('openpgp.crypto.roundtrip',false,{error:e.message})}
 const ots=[path.join(CRYPTO,'javascript-opentimestamps/ots-cli.js'),path.join(ROOT,'node_modules/opentimestamps/ots-cli.js')],proof=path.join(CRYPTO,'javascript-opentimestamps/examples/hello-world.txt.ots');let otsOk=false,infoOk=false;const otsDetails=[];
 for(const f of ots){if(!fs.existsSync(f)){otsDetails.push({path:f,exists:false});continue}const r=run(process.execPath,[f,'--help']);let inf={ok:false};if(r.ok&&fs.existsSync(proof))inf=run(process.execPath,[f,'info','-v',proof]);otsDetails.push({path:f,exists:true,exec:r.ok,info:inf.ok,status:r.status,stderr:r.stderr.slice(0,500)});if(r.ok)otsOk=true;if(inf.ok)infoOk=true}
 const jars=[path.join(CRYPTO,'java-opentimestamps/target/OtsCli.jar'),path.join(CRYPTO,'opentimestamps/OtsCli.jar')];for(const f of jars){if(!fs.existsSync(f))continue;const r=run('/usr/bin/java',['-jar',f,'--help']);let inf={ok:false};if(r.ok&&fs.existsSync(proof))inf=run('/usr/bin/java',['-jar',f,'info','-v',proof]);otsDetails.push({path:f,exists:true,exec:r.ok,info:inf.ok,status:r.status});if(r.ok)otsOk=true;if(inf.ok)infoOk=true}
 rec('ots.executable.engine',otsOk,{candidates:otsDetails});rec('ots.local.proof.info',infoOk,{proof,exists:fs.existsSync(proof)});
 const manifest=path.join(CRYPTO,'CRYPTO_MANIFEST.json');rec('crypto.manifest',fs.existsSync(manifest),{path:manifest});if(fs.existsSync(manifest)){try{const m=JSON.parse(fs.readFileSync(manifest));let bad=0;for(const e of m.files||[]){const f=path.join(CRYPTO,e.path);if(!fs.existsSync(f)){bad++;continue}const h=crypto.createHash('sha256'),fd=fs.openSync(f,'r'),buf=Buffer.allocUnsafe(1024*1024);try{for(;;){const n=fs.readSync(fd,buf,0,buf.length,null);if(!n)break;h.update(buf.subarray(0,n))}}finally{fs.closeSync(fd)}if(h.digest('hex')!==e.sha256)bad++}rec('crypto.manifest.hashes',bad===0,{files:(m.files||[]).length,bad})}catch(e){rec('crypto.manifest.hashes',false,{error:e.message})}}
 const out={schema:'pasevsu-runtime-selftest/v2',ok:failures.length===0,checks,failures};console.log(JSON.stringify(out,null,2));process.exit(out.ok?0:9);
})().catch(e=>{console.error(e);process.exit(9)});
