#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const ROOT=path.resolve(process.argv[2]||'/opt/pasevsu'),CRYPTO=path.join(ROOT,'_crypto');
const JAVA_OTS_EXTERNAL=process.env.CHRONOSEAL_JAVA_OTS_JAR||'/share/chronoseal/runtime/OtsCli.jar';
const JAVA_OTS_EXPECTED_SHA256=String(process.env.CHRONOSEAL_JAVA_OTS_SHA256||'').trim().toLowerCase();
const CONTRACT_PATH=[path.join(ROOT,'RUNTIME_CONTRACT.json'),path.join(ROOT,'tools','RUNTIME_CONTRACT.json')].find(fs.existsSync)||path.join(ROOT,'RUNTIME_CONTRACT.json');
const failures=[],checks=[];
function rec(name,ok,detail={}){checks.push({name,ok,...detail});if(!ok&&!failures.includes(name))failures.push(name)}
function run(bin,args,timeout=30000){try{const r=cp.spawnSync(bin,args,{encoding:'utf8',timeout,maxBuffer:8*1024*1024});return {ok:r.status===0,status:r.status,signal:r.signal||null,stdout:String(r.stdout||''),stderr:String(r.stderr||''),error:r.error?.message||null}}catch(e){return {ok:false,status:null,error:e.message,stdout:'',stderr:''}}}
function sha256File(f){const h=crypto.createHash('sha256'),fd=fs.openSync(f,'r'),buf=Buffer.allocUnsafe(1024*1024);try{for(;;){const n=fs.readSync(fd,buf,0,buf.length,null);if(!n)break;h.update(buf.subarray(0,n))}}finally{fs.closeSync(fd)}return h.digest('hex')}
function walkFind(root,names,max=12){const want=new Set(names.map(x=>x.toLowerCase())),out=[];function w(d,depth){if(depth>max)return;let es=[];try{es=fs.readdirSync(d,{withFileTypes:true})}catch{return}for(const e of es){const p=path.join(d,e.name);if(e.isDirectory())w(p,depth+1);else if(want.has(e.name.toLowerCase()))out.push(p)}}if(fs.existsSync(root))w(root,0);return out}
(async()=>{
 let contract=null;try{contract=JSON.parse(fs.readFileSync(CONTRACT_PATH,'utf8'));rec('runtime.contract',true,{path:CONTRACT_PATH,schema:contract.schema})}catch(e){rec('runtime.contract',false,{path:CONTRACT_PATH,error:e.message})}
 const openssl=process.platform==='win32'?'openssl':'/usr/bin/openssl',java=process.platform==='win32'?'java':'/usr/bin/java';
 rec('openssl.exec',run(openssl,['version']).ok,{binary:openssl});rec('java.exec',run(java,['-version']).ok,{binary:java});
 const vendor=path.join(ROOT,'app/vendor/openpgp.min.js');rec('openpgp.browser.bundle',fs.existsSync(vendor)&&fs.statSync(vendor).size>100000,{path:vendor,bytes:fs.existsSync(vendor)?fs.statSync(vendor).size:0});
 try{const pkgPath=require.resolve('openpgp/package.json',{paths:[ROOT]}),j=JSON.parse(fs.readFileSync(pkgPath));const expected=contract?.openpgpVersion||'6.3.1';rec('openpgp.node.package',j.version===expected,{version:j.version,expected,pkgPath});const mod=await import(path.join(ROOT,'node_modules/openpgp/dist/node/openpgp.mjs'));const {privateKey,publicKey}=await mod.generateKey({type:'ecc',curve:'curve25519Legacy',userIDs:[{name:'PasevSU Runtime Selftest'}],passphrase:'selftest-only'});let pk=await mod.readPrivateKey({armoredKey:privateKey});pk=await mod.decryptKey({privateKey:pk,passphrase:'selftest-only'});const pub=await mod.readKey({armoredKey:publicKey}),msg=await mod.createMessage({text:'pasevsu-runtime-selftest'}),sig=await mod.sign({message:msg,signingKeys:pk,detached:true}),sg=await mod.readSignature({armoredSignature:sig}),vr=await mod.verify({message:msg,signature:sg,verificationKeys:pub});await vr.signatures[0].verified;rec('openpgp.crypto.roundtrip',true,{fingerprint:pub.getFingerprint().toUpperCase()})}catch(e){if(!checks.some(x=>x.name==='openpgp.node.package'))rec('openpgp.node.package',false,{error:e.message});rec('openpgp.crypto.roundtrip',false,{error:e.message})}
 const fixtureRel=contract?.otsFixture?.path||'tools/fixtures/hello-world.txt.ots',proof=path.join(ROOT,fixtureRel);let fixtureOk=fs.existsSync(proof);if(fixtureOk&&contract?.otsFixture?.sha256)fixtureOk=sha256File(proof)===contract.otsFixture.sha256;rec('ots.fixture.integrity',fixtureOk,{proof,exists:fs.existsSync(proof),sha256:fs.existsSync(proof)?sha256File(proof):null,expected:contract?.otsFixture?.sha256||null});
 let otsPackageOk=false;try{const pkgPath=require.resolve('opentimestamps/package.json',{paths:[ROOT]}),j=JSON.parse(fs.readFileSync(pkgPath));const expected=contract?.opentimestampsVersion||'0.4.6';otsPackageOk=j.version===expected;rec('opentimestamps.node.package',otsPackageOk,{version:j.version,expected,pkgPath})}catch(e){rec('opentimestamps.node.package',false,{error:e.message})}
 const pinnedNode=path.join(ROOT,'node_modules/opentimestamps/ots-cli.js');const nodeCandidates=[pinnedNode,...walkFind(CRYPTO,['ots-cli.js']).filter(x=>x!==pinnedNode)];const jarCandidates=[JAVA_OTS_EXTERNAL,...walkFind(CRYPTO,['OtsCli.jar']).filter(x=>x!==JAVA_OTS_EXTERNAL)];let otsOk=false,infoOk=false,pinnedPrimaryOk=false;const otsDetails=[];
 for(const f of [...new Set(nodeCandidates)]){if(!fs.existsSync(f)){otsDetails.push({type:'node',path:f,exists:false});continue}const help=run(process.execPath,[f,'--help']);const inf=help.ok&&fixtureOk?run(process.execPath,[f,'info','-v',proof]):{ok:false,status:null,stderr:'fixture/help prerequisite failed'};otsDetails.push({type:'node',role:f===pinnedNode?'PRIMARY_PINNED':'SOURCE_FALLBACK',path:f,exists:true,exec:help.ok,info:inf.ok,helpStatus:help.status,infoStatus:inf.status,stderr:(inf.stderr||help.stderr||'').slice(0,1000)});if(help.ok)otsOk=true;if(inf.ok)infoOk=true;if(f===pinnedNode&&help.ok&&inf.ok&&otsPackageOk)pinnedPrimaryOk=true}
 for(const f of [...new Set(jarCandidates)]){if(!fs.existsSync(f)){otsDetails.push({type:'java',path:f,exists:false,trusted:false,reason:'MISSING'});continue}const actual=sha256File(f),trusted=/^[0-9a-f]{64}$/.test(JAVA_OTS_EXPECTED_SHA256)&&actual===JAVA_OTS_EXPECTED_SHA256;if(!trusted){otsDetails.push({type:'java',path:f,exists:true,trusted:false,sha256:actual,expectedSha256:JAVA_OTS_EXPECTED_SHA256||null,reason:JAVA_OTS_EXPECTED_SHA256?'SHA256_PIN_MISMATCH':'SHA256_PIN_REQUIRED'});continue}const help=run(java,['-jar',f,'--help']);const inf=help.ok&&fixtureOk?run(java,['-jar',f,'info','-v',proof]):{ok:false,status:null,stderr:'fixture/help prerequisite failed'};otsDetails.push({type:'java',path:f,exists:true,trusted:true,sha256:actual,exec:help.ok,info:inf.ok,helpStatus:help.status,infoStatus:inf.status,stderr:(inf.stderr||help.stderr||'').slice(0,1000)});if(help.ok)otsOk=true;if(inf.ok)infoOk=true}
 rec('ots.primary.pinned',pinnedPrimaryOk,{path:pinnedNode,packageVersionOk:otsPackageOk});rec('ots.executable.engine',otsOk,{candidates:otsDetails});rec('ots.local.proof.info',infoOk,{proof,candidates:otsDetails});
 const manifest=path.join(CRYPTO,'CRYPTO_MANIFEST.json');rec('crypto.manifest',fs.existsSync(manifest),{path:manifest});if(fs.existsSync(manifest)){try{const m=JSON.parse(fs.readFileSync(manifest));let bad=0;for(const e of m.files||[]){const f=path.resolve(CRYPTO,e.path);if(!(f===CRYPTO||f.startsWith(CRYPTO+path.sep))||!fs.existsSync(f)){bad++;continue}if(sha256File(f)!==String(e.sha256).toLowerCase())bad++}rec('crypto.manifest.hashes',bad===0,{files:(m.files||[]).length,bad})}catch(e){rec('crypto.manifest.hashes',false,{error:e.message})}}
 for(const name of contract?.requiredCapabilities||[]){if(!checks.some(x=>x.name===name&&x.ok))rec(`contract.required:${name}`,false,{reason:'required capability did not PASS'})}
 const out={schema:'pasevsu-runtime-selftest/v3',generatedAt:new Date().toISOString(),root:ROOT,platform:process.platform,arch:process.arch,ok:failures.length===0,checks,failures};console.log(JSON.stringify(out,null,2));process.exit(out.ok?0:9);
})().catch(e=>{console.error(JSON.stringify({schema:'pasevsu-runtime-selftest/v3',ok:false,fatal:e.stack||e.message},null,2));process.exit(9)});
